# frozen_string_literal: true

require 'rails_helper'

RSpec.describe 'Orders', type: :system do
  before do
    driven_by(:rack_test)
    @user = FactoryBot.create(:user)
    @customer = FactoryBot.create(:customer)
    @item1 = FactoryBot.create(:item1)
    @item2 = FactoryBot.create(:item2)
    @cad = FactoryBot.create(:cad)
    @jpy = FactoryBot.create(:jpy)
    @rate = @jpy.rate / @cad.rate
    visit '/login'
    fill_in 'Email', with: @user.email
    fill_in 'Password', with: @user.password
    click_button 'Log in'
  end

  it "creates a new order with a new list at the same time" do
    expect do
      visit new_order_path
      select 'Test', from: 'order[customer_id]'
      fill_in 'order[order_date]', with: Date.today
      select 'test1', from: 'order[lists_attributes][0][item_id]'
      fill_in 'order[lists_attributes][0][amount]', with: 1
      fill_in 'order[lists_attributes][0][discount]', with: 5
      click_button 'Save'
    end.to change(Order, :count).by(1) and change(List, :count).by(1)
  end

  # TODO: Hash keys after 2nd lists are generated by timestamps. I don't know how to select that now.
  #
  # it "creates a new order with 2 new lists at the same time", js: true do
  #   expect do
  #     visit new_order_path
  #     select 'Test', from: 'order[customer_id]'
  #     fill_in 'order[order_date]', with: Date.today
  #     select 'test1', from: 'order[lists_attributes][0][item_id]'
  #     fill_in 'order[lists_attributes][0][amount]', with: 1
  #     fill_in 'order[lists_attributes][0][discount]', with: 5
  #     find('a', text: 'Add Item').click
  #     select 'test2', from: 'order[lists_attributes][1][item_id]'
  #     fill_in 'order[lists_attributes][1][amount]', with: 2
  #     fill_in 'order[lists_attributes][1][discount]', with: 8
  #     click_button 'Save'
  #   end.to change(Order, :count).by(1) and change(List, :count).by(2)
  # end

  it "displays lates exchange rate in order new view" do
    visit new_order_path
    expect(page).to have_content @rate
  end
end
